[2023-11-30T18:07:26.449+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: regression_score.train_model manual__2023-11-30T13:06:17.923217+00:00 [queued]>
[2023-11-30T18:07:26.467+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: regression_score.train_model manual__2023-11-30T13:06:17.923217+00:00 [queued]>
[2023-11-30T18:07:26.467+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-30T18:07:26.520+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-11-30 13:06:17.923217+00:00
[2023-11-30T18:07:26.528+0500] {standard_task_runner.py:57} INFO - Started process 4921 to run task
[2023-11-30T18:07:26.538+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'regression_score', 'train_model', 'manual__2023-11-30T13:06:17.923217+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/regression_score.py', '--cfg-path', '/tmp/tmp7pz08l87']
[2023-11-30T18:07:26.540+0500] {standard_task_runner.py:85} INFO - Job 36: Subtask train_model
[2023-11-30T18:07:26.643+0500] {task_command.py:416} INFO - Running <TaskInstance: regression_score.train_model manual__2023-11-30T13:06:17.923217+00:00 [running]> on host debian
[2023-11-30T18:07:26.830+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='regression_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T13:06:17.923217+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T13:06:17.923217+00:00'
[2023-11-30T18:07:26.837+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T18:07:26.839+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 ~/MLops_3/scripts/train_model.py']
[2023-11-30T18:07:26.880+0500] {subprocess.py:86} INFO - Output:
[2023-11-30T18:07:42.654+0500] {subprocess.py:93} INFO - /home/flow/MLops_3/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-11-30T18:07:42.720+0500] {subprocess.py:93} INFO - 
[2023-11-30T18:07:42.721+0500] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-11-30T18:07:42.721+0500] {subprocess.py:93} INFO -   warnings.warn(
[2023-11-30T18:07:42.755+0500] {subprocess.py:93} INFO - /home/flow/MLops_3/venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
[2023-11-30T18:07:42.755+0500] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-11-30T18:07:42.755+0500] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-11-30T18:09:53.406+0500] {subprocess.py:93} INFO - 2023/11/30 18:09:53 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpwm98nk3g/model/model.pkl, flavor: sklearn), fall back to return ['scikit-learn==1.3.2', 'cloudpickle==2.2.1']. Set logging level to DEBUG to see the full traceback.
[2023-11-30T18:09:55.960+0500] {subprocess.py:93} INFO - Registered model 'model' already exists. Creating a new version of this model...
[2023-11-30T18:09:56.268+0500] {subprocess.py:93} INFO - 2023/11/30 18:09:56 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: model, version 3
[2023-11-30T18:09:56.273+0500] {subprocess.py:93} INFO - Created version '3' of model 'model'.
[2023-11-30T18:10:02.701+0500] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-30T18:10:02.839+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=regression_score, task_id=train_model, execution_date=20231130T130617, start_date=20231130T130726, end_date=20231130T131002
[2023-11-30T18:10:03.008+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-30T18:10:03.065+0500] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
